// Mocks
import 'babel-polyfill';
import './mocks/gon';
import './mocks/mrch';

// Libs
import '../app/scripts/render.libs';
import './libsConfigs';

// Components
import './react/components/CatalogFilter/CatalogFilter.test';
import './react/components/Userbar/Userbar.test';
import './react/components/Logo/Logo.test';
import './react/components/Notice/Notice.test';
import './react/components/DesignSettings/DesignSettings.test';
import './react/components/Product/ProductCart/ProductCart.test';
import './react/components/Product/ProductCard/ProductCardContainer.test';
import './react/components/Product/ProductCard/ProductCard.test';
import './react/components/Product/ProductCard/ProductCardDetails.test';
import './react/components/Product/ProductCard/ProductCardGallerySlider.test';
import './react/components/Product/ProductProperties/index.test';
import './react/components/Cart/CartCoupon.test';
import './react/components/Cart/index.test';
import './react/components/Order/index.test';
import './react/components/Wishlist/index.test';

import './react/components/Clientbar/index.test';
import './react/components/Product/ProductBlock/index.test';
import './react/components/TopBanner/index.test';
import './react/components/Order/OrderCoupon.test';
import './react/components/InstagramContainer/index.test';
import './react/components/ScrollToTop/index.test';
import './react/components/ImageSlider/index.test';
import './react/components/CurrencySwitcher/index.test';
import './react/components/LocaleSwitcher/index.test';
import './react/components/MenuTop/index.test';
import './react/components/MenuBottom/index.test';
import './react/components/NavBar/index.test';
import './react/components/ProductList/index.test';
import './react/components/ProductGroup/index.test';
import './react/components/ChildrenProducts/index.test';
import './react/components/Pagination/index.test';
import './react/components/CategoriesShow/index.test';
