export const DESIGN_CHANGE_OPTION = 'DESIGN_CHANGE_OPTION';
export const DESIGN_SAVE = 'DESIGN_SAVE';
export const DESIGN_SAVE_SUCCESS = 'DESIGN_SAVE_SUCCESS';
export const DESIGN_SAVE_FAIL = 'DESIGN_SAVE_FAIL';

export const INFO_LOAD = 'INFO_LOAD';
export const INFO_LOAD_SUCCESS = 'INFO_LOAD_SUCCESS';
export const INFO_LOAD_FAIL = 'INFO_LOAD_FAIL';