export const DESIGN_ANY_TYPE = 'DESIGN_ANY_TYPE';
export const DESIGN_FONT_TYPE = 'DESIGN_FONT_TYPE';
export const DESIGN_RADIO_TYPE = 'DESIGN_RADIO_TYPE';
export const DESIGN_COLOR_TYPE = 'DESIGN_COLOR_TYPE';
export const DESIGN_SLIDER_TYPE = 'DESIGN_SLIDER_TYPE';
export const DESIGN_CHECKBOX_TYPE = 'DESIGN_CHECKBOX_TYPE';
export const DESIGN_FONT_SIZE_TYPE = 'DESIGN_FONT_SIZE_TYPE';
export const DESIGN_ATTACHMENT_TYPE = 'DESIGN_ATTACHMENT_TYPE';